presentation/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name='presentation'

urlpatterns = [
    #ex: /sed/
    url(r'^$', views.indexView.as_view(), name='index'),
    #ex: /sed/2/
    #url(r'^m/(?P<pk>[0-9]+)/$', views.memberView.as_view(), name='member'),
    path('m/<int:pk>/', views.memberView.as_view(), name='member'),
    path('p/<int:pk>/', views.projectView.as_view(), name='project'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

presentation/models.py
from django.db import models
#from django import datetime
from next_prev import next_in_order, prev_in_order

class researcher(models.Model):
    name = models.CharField(max_length=200)
    #role = models.ForeignKey('researcherRoles', on_delete=models.PROTECT) #use dropdown?
   
    profileImage = models.ImageField("Profile picture", upload_to='sed', default='sed/default/avancez.png')
    researchImage = models.ImageField("Image about research field", upload_to='sed', default='sed/default/projectBanner.png')
    bannerProfessional = models.ImageField("Banner in profesional environment", upload_to='sed', default='sed/default/ChalmersPhDthesis.jpg')
    imageTextProfessional = models.CharField("Caption for profesionall banner", max_length=100, blank=True) 
    bannerCasual = models.ImageField("Banner in private context", upload_to='sed', blank=True)
    imageTextCasual = models.CharField("Caption for private banner", max_length=100, blank=True) 
    emailAdress = models.EmailField("Email address") #find email field
    #phoneNumber = forms.RegexField(regex=r'^\+?1?\d{9,15}$', 
    #                            error_message = ("Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."), blank=True)
    phoneNumber = models.CharField("Phone number", max_length=20, blank=True)
    
    persInterest1 = models.CharField("Personal interest", max_length=100, blank=True) #list field?
    persInterest2 = models.CharField("Personal interest", max_length=100, blank=True)
    persInterest3 = models.CharField("Personal interest", max_length=100, blank=True)
    profInterest1 = models.CharField("Research interest", max_length=100, blank=True) #list field?
    profInterest2 = models.CharField("Research interest", max_length=100, blank=True)
    profInterest3 = models.CharField("Research interest", max_length=100, blank=True)
    
    persDescription = models.TextField("Personal description")
    #startDate = models.DateField(default=datetime.date.today)
    
    # role selector field:
    LEADER = 'AA'
    SENIOR = 'BB'
    STUDENT = 'CC'
    GUEST = 'DD'
    ROLE_CHOICES = (
        (LEADER, 'Group Leader'),
        (SENIOR, 'Senior Researcher'),
        (STUDENT, 'PhD Student'),
        (GUEST, 'Guest Researcher'),
    )
    roleX = models.CharField(
        "Role in group",
        max_length=2,
        choices=ROLE_CHOICES,
        default=STUDENT,
    )
    def nextR(self):    
        nextR = next_in_order(self, loop=True)
        return nextR
    def prevR(self):
        prevR = prev_in_order(self, loop=True)
        return prevR
        
    def __str__(self):
        return self.name
        
    def contactCard(self):
        cc = {'name': self.name, 'phone_number':self.phoneNumber, 'email':self.emailAdress, 'company':'Chalmers University of Technology', 'url':'',}
        return cc
    def contactQR(self):
        contact="N:{0};EMAIL:{1};TEL:{2};ADR:Department of Industrial and Materials Science, Chalmers University of Technology".format(self.name, self.emailAdress, self.phoneNumber)
        qr = "https://api.qrserver.com/v1/create-qr-code/?data=MECARD:{}&size=120x120&bgcolor=f6f6f6".format(contact)
        return qr
        
    class Meta:
        ordering = ['roleX', 'name', 'pk']
    #class Meta:
    #    order_with_respect_to = 'role'
            
class partners(models.Model):
    name= models.CharField(max_length=100)
    logo = models.ImageField(upload_to='sed', blank=True)
    type = models.CharField(
        max_length=2,
        choices= (('A', 'Academic'), ('I', 'Industrial')),
        default ='A',
        )        
    def __str__(self):
         return self.name
    class Meta:
        ordering = ['type', 'name', 'pk']
        
class project(models.Model):
    name=models.CharField(max_length=200)
    project_logo = models.ImageField(upload_to='sed/projects', default='/sed/default/projectLogo.png')
    project_illustration = models.ImageField(upload_to='sed/projects', default='/sed/default/projectBanner.png')
    project_lead = models.ForeignKey('researcher', on_delete=models.PROTECT, related_name='lead', null=True)
    description = models.TextField('Project description')
    researchers = models.ManyToManyField(researcher)
    partners = models.ManyToManyField(partners, blank=True)
    
    def __str__(self):
        return self.name

            
# class researcherRoles(models.Model):
        # roleName=models.CharField(max_length=200)
        # orderBy = models.IntegerField()
        # def __str__(self):
            # return self.roleName
        # class Meta:
            # ordering = ['orderBy']

presentation/views.py
from django.shortcuts import render

from .models import researcher
from .models import project
from django.views import generic

class indexView(generic.TemplateView):
    template_name = 'presentation/overview.html'
    #context_object_name = 'all_researchers'
    #model = researcher 
    
    def get_context_data(self, **kwargs):
        context = super(indexView, self).get_context_data(**kwargs)
        context['all_researchers'] = researcher.objects.all()
        context['all_projects'] = project.objects.all()
        return context
        # categories = ['leader', 'senior', 'student', 'guest']
        # for c in categories:
           # try:
               # context[c] = researcher.objects.filter(role__roleName__icontains=c)
           # except researcher.DoesNotExist: 
                # context[c] = None        
    
class memberView(generic.DetailView):
    model = researcher
    template_name = 'presentation/researcher.html'    
    
class projectView(generic.DetailView):
    model = project
    template_name = 'presentation/project.html'
    
class slideView(generic.ListView):
    template_name = 'presentation/slideshow.html'
    context_object_name = 'all_researchers'
    model = researcher

presentation/templates/presentation/overview.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>Systems Engineering Design</title>
    <meta name="description" content="Systems Engineering Design">
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <!-- forwarding after 6 seconds to next researcher: -->
    <!--<meta http-equiv="refresh" content="6;url={% url 'presentation:member' all_researchers.0.id %}" />-->
    <link rel="stylesheet" href="{% static 'presentation/css/main.css' %}?20190122b">
    <!--
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

	-->
</head>
<body>
    
	<div class="overviewMain">         
        <h1>Systems Engineering Design</h1>
        
        
        <div class="description">
        The group studies the product development process and its participants in product developing companies in order to understand their problems and needs. This knowledge gained is then transformed into better work procedures, development methods and computer-based tools. A special interest is platform-based development, which is a widely adopted strategy for balancing the conflict between reuse and demands on customization. The aim of the research conducted within this theme is to significantly contribute to a new system family based platform description approach that, in a PLM environment, will provide a ground for reuse of assets in terms of knowledge in all product development phases as well as in production, i.e. from early requirement specification and concept development phases to the final detail system design phase and in production.
        </div>
         
         
        <div class="overviewMembers">
        {% regroup all_researchers by get_roleX_display as rSorted %}
            
            {% for rGroup in rSorted %}
            <h2 class="overviewH2"> {{rGroup.grouper}}{% if rGroup.list|length > 1 %}s{% endif %}
			</h2>
            <div class="membercontainer">
                {% for r in rGroup.list %}
                    <div class="member">
						<a class="imgsize" href="{% url 'presentation:member' r.id %}">
							<img src="{{ r.profileImage.url }}" />
						</a>
                        {{ r.name }}
                    </div>
                    {% empty %}
                    Currently no {{rGroup.grouper}}
                {% endfor %}
            </div>
            {% empty %}
            Currently no one active in the group
            {% endfor %}
      
            
            <h2 class="overviewH2">Research Projects</h2>
        
            <div class="membercontainer">
        
            {% for p in all_projects %}
                <div class="member">
                    <div class="imgsize">
                    <a href="{% url 'presentation:project' p.id %}"><img src="{{ p.project_logo.url }}" /></a>
                    </div>{{ p.name }}
				</div>
            {% empty %}
                Currently there are no active projects
            {%endfor%}
            </div>
        
        </div>
    </div>
    
    <div class="banner_bottom">

    	Industrial and Materials Science | Product Development<br>
    	Systems Engineering Design

	</div>
		
	<div class="partners">
        <div class="member"><img alt="AoA Production" src="{% static 'presentation/img/AOA_production.png' %}" /></div>
        <div class="member"><img alt="Chalmers tekniska högskola" src="{% static 'presentation/img/chalmers.png' %}" /></div>
        <div class="member"><img alt="Wingquist Laboratory" src="{% static 'presentation/img/wingquist.png' %}" /></div>
		
	</div>
		
</body>
    
</html>

presentation/templates/presentation/project.html
{% load staticfiles %}
{% load qr_tags %}
<!DOCTYPE html>
<html>
<head>
	<title>Systems Engineering Design</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="description" content="Systems Engineering Design">
    <!-- forwarding after 9 seconds to next researcher: -->
    <meta http-equiv="refresh" content="9;url={% url 'presentation:index' %}" />

    <link rel="stylesheet" href={% static 'presentation/css/main.css' %}>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


</head>
<body onmouseover="window.location = '{% url 'presentation:index' %}';" onscroll="window.location = '{% url 'presentation:index' %}';" onclick="window.location = '{% url 'presentation:index' %}';" style="display:none;">
			
			
        <div class="container">
            <img src="{{ project.project_illustration.url }}" />
        </div>
        
        
        <div class="imgtext"><div class="rightpad"></div></div>
        
        <div class="memberprofilepic"><img src="{{ project.project_logo.url }}" /></div>
        
        <div class="moveup">
        
        <div class="main">
        
        	<div id="name" class="heading"><b>{{ project.name }} Project</b></div>
             
        	<div id="text" class="text">{{ project.description }}
 
            </div>
        
        	<div class="flex-body">
        	
        		<div class="left">
    				<div class="left_side_img">
						<img class="research" src="" />
					</div>
    				<div class="left_side">
                        <div class="qrcode"><img src="{{ project.project_lead.contactQR }}"/></div>
						<div class="left_side_text">
        					<div class="memberinfo">
								<img alt="Email:" src="{% static 'presentation/img/email.png' %}" /> &nbsp;{{ project.project_lead.emailAdress }}<p>
								<img alt="Phone:" src="{% static 'presentation/img/phone.png' %}" /> &nbsp;{{ project.project_lead.phoneNumber }}
							</div>
						</div>
					</div>
  				</div>

  				<div class="right">
  					<div class="right_side">
        				<div id="professional" class="right_side_text">
        				
        				{% regroup project.partners.all by get_type_display as rSorted %}
        
        				{% for rGroup in rSorted %}
        				<b> {{rGroup.grouper}} Collaborators</b><br>
            			{% for r in rGroup.list %}
							<ul>
                    			<li>{{ r.name }}</li>
  							</ul>
                			{% empty %}
                		Currently no {{rGroup.grouper}} collaborators
            			{% endfor %}
        			{% empty %}
        			Currently no collaborators at all
        			{% endfor %}
						
					</div>
				</div>
			</div>
			
			</div>			
		
		<div class="membercontainer">
			<div class="projects">
        		<b>Members of the research project:</b><br>
        		
        		{% for r in project.researchers.all %}
        		
                <div class="member">
                    <div class="imgsize">
                        <a href="{% url 'presentation:member' r.id %}"><img src="{{ r.profileImage.url }}" /></a>
                    </div>
                    {{ r.name }}
                </div>
                
                {% empty %}
                	
                    Currently there are no members in this research project
                	
            	{% endfor %}
            	
            </div>
        </div>
		
		</div>
     	
     	<div class="banner_bottom">
        	Industrial and Materials Science | Product Development<br>
        	Systems Engineering Design
		</div>
	
		<div class="collaborators">
		
		{% for p in project.partners.all %}
            {% if p.logo %}
			<div class="member"><img alt="{{ p.name }}" src="{{ p.logo.url }}" /></div>
            {%else%}
            <div class="member"><b>{{ p.name }}</b></div>
            {%endif%}
		{%endfor%}
		
		</div>
		
		<div class="partners">
			<div class="member"><img alt="AoA Production" src="{% static 'presentation/img/AOA_production.png' %}" /></div>
        	<div class="member"><img alt="Chalmers tekniska högskola" src="{% static 'presentation/img/chalmers.png' %}" /></div>
        	<div class="member"><img alt="Wingquist Laboratory" src="{% static 'presentation/img/wingquist.png' %}" /></div>
		</div>
		
		</div>
</body>
</html>

presentation/templates/presentation/researcher.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Systems Engineering Design</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="description" content="Systems Engineering Design">
    <!-- forwarding after 9 seconds to next researcher: -->
    <!-- <meta http-equiv="refresh" content="9;url={% url 'presentation:member' researcher.nextR.id %}" />-->

    <link rel="stylesheet" href="{% static 'presentation/css/main.css' %}?20190122c">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'presentation/js/jquery.touchSwipe.min.js' %}"></script>

</head>
<body> 
    <!-- onmouseover="window.location = '{% url 'presentation:index' %}';" onscroll="window.location = '{% url 'presentation:index' %}';" onclick="window.location = '{% url 'presentation:index' %}';" style="display:none;" -->
			
        <div id="TopBanner">
            <div id="scrollBanner">
                <div class="imgCont">
                    <img src="{{ researcher.bannerProfessional.url }}" /> 
                    <div class="imgtext">{{ researcher.imageTextProfessional }}</div>
                </div>
                <div class="imgCont">
                    {% if researcher.bannerCasual %}
                    <img src="{{ researcher.bannerCasual.url }}"/>
                    <div class="imgtext">{{ researcher.imageTextCasual }}</div>
                    {% else %}
                    <img src="{{ researcher.bannerProfessional.url }}"/>
                    <div class="imgtext">{{ researcher.imageTextProfessional }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
            
        
        <div class="memberprofilepic">
			<img src="{{ researcher.profileImage.url }}" />
		</div>

        <div id="name" class="heading">
            <span><b>{{ researcher.name }}</b> | {{ researcher.get_roleX_display }}</span>
        </div>
        
        <div id="mainWrapper">
            <div id="main">
                <!-- boxes left and right that show when swiping -->
                <div id="prevMember">
                <b>{{ researcher.prevR.name }}</b> | {{ researcher.prevR.get_roleX_display}}
                </div>
                <div id="nextMember">
                <b>{{ researcher.nextR.name }}</b> | {{ researcher.nextR.get_roleX_display}}
                </div>
                
                <div class="descriptionText">{{ researcher.persDescription }}</div>

                <img class="researchImg" src="{{ researcher.researchImage.url }}" />
                
                <div class="memberinfo">
                    <img id="qrCode" src="{{researcher.contactQR}}"/>
                        <img alt="Email:" src="{% static 'presentation/img/email.png' %}" /> &nbsp;{{ researcher.emailAdress }}<p>
                        {% if researcher.phoneNumber %}
                        <img alt="Phone:" src="{% static 'presentation/img/phone.png' %}" /> &nbsp;{{ researcher.phoneNumber }}
                        {% endif %}
                </div>

                <div id="interests">
                    <b>Professional Interests</b>
                    <ul>
                    {% if researcher.profInterest1 %}
                        <li>{{ researcher.profInterest1 }}</li><p>
                    {% endif %}
                    {% if researcher.profInterest2 %}
                        <li>{{ researcher.profInterest2 }}</li><p>
                    {% endif %}
                    {% if researcher.profInterest3 %}
                        <li>{{ researcher.profInterest3 }}</li>
                    {% endif %}
                    </ul>
                    <br/>
                    <b>Personal Interests</b>
                    <ul>
                    {% if researcher.persInterest1 %}
                        <li>{{ researcher.persInterest1 }}</li><p>
                    {% endif %}
                    {% if researcher.persInterest2 %}
                        <li>{{ researcher.persInterest2 }}</li><p>
                    {% endif %}
                    {% if researcher.persInterest3 %}
                        <li>{{ researcher.persInterest3 }}</li>
                    {% endif %}
                    </ul>                    
                </div>
      

            
                <div id="projects">
                    <b>Research projects:</b><br>
                    {% for p in researcher.project_set.all %}
                        <div class="member">
                            <div class="imgsize">
                             <a href="{% url 'presentation:project' p.id %}"><img src="{{ p.project_logo.url }}" /></a> 
                            </div>
                            {{ p.name }}
                        </div>
                    {% empty %}
                        <p> {{ researcher.name }} has no active research projects</p>
                    {%endfor%}
                </div>

            
                <div class="banner_bottom">
                    Industrial and Materials Science | Product Development<br>
                    Systems Engineering Design
                </div>
            
                <div class="partners">
                    <div class="member"><img alt="AoA Production" src="{% static 'presentation/img/AOA_production.png' %}" /></div>
                    <div class="member"><img alt="Chalmers tekniska högskola" src="{% static 'presentation/img/chalmers.png' %}" /></div>
                    <div class="member"><img alt="Wingquist Laboratory" src="{% static 'presentation/img/wingquist.png' %}" /></div>
                </div>
            
            </div>
        </div>
        <div class="popup" id="returnHomeBanner">
            To return to the overview<br/>
            <b>DOUBLETAP</b>
        </div>
		<div class="popup" id="autoChange">
			Next researcher in <br/>
			<b><span id="autoChangeCountdown">3</span></b> <br/>
			Tap to stop.
		</div>
		<div class="popup" id="introNavi">
			<b>&lt; &gt;</b> swipe for next
			<b>(**)</b> double tap to return 
		</div>
    <script>
   
        /* ****************************************
        SWIPE THE BANNER */
        
        var IMG_WIDTH = 1046;
        var currentImg = 0;
        var maxImages = 2;
        var speed = 500;
		var autoSiteChangeTime = 30000;
		var doAutoChange = false;

        var imgs;
        var mainDiv;
		var popupDT = "#returnHomeBanner";

        var swipeOptionsImg = {
            triggerOnTouchEnd: true,
            swipeStatus: swipeStatusImg,
            allowPageScroll: "none",
            threshold: 100
        };
        var swipeOptionsMain = {
            triggerOnTouchEnd: true,
            swipeStatus: changeR,
            tap: alertDT,
            doubleTap: backHome,
            allowPageScroll: "none",
            threshold: 100
        };

        $(function () {
			popup("#introNavi", 1200);
			setTimeout(autoSiteChange, autoSiteChangeTime);
            imgs = $("#scrollBanner");
            imgs.swipe(swipeOptionsImg);
            
            mainDiv = $("#main");
            mainDiv.swipe(swipeOptionsMain);
        });

        function changeR(event, phase, direction, distance) {
			//alert("MAIN");
            if (phase == "move" && (direction == "left" || direction == "right")) {
                var duration = 0;

                if (direction == "left") {
                    scrollMain((IMG_WIDTH * currentImg) + distance, duration);
                } else if (direction == "right") {
                    scrollMain((IMG_WIDTH * currentImg) - distance, duration);
                }

            } else if (phase == "cancel") {
                scrollMain(IMG_WIDTH * currentImg, speed);
            } else if (phase == "end") {
                if (direction == "right") {
                    window.location.href="{% url 'presentation:member' researcher.prevR.id %}";
                } else if (direction == "left") {
                    window.location.href="{% url 'presentation:member' researcher.nextR.id %}";
                }
            } 
        }
        function scrollMain(distance, duration) {
            mainDiv.css("transition-duration", (duration / 1000).toFixed(1) + "s");

            //inverse the number we set in the css
            var value = (distance < 0 ? "" : "-") + Math.abs(distance).toString();
            mainDiv.css("transform", "translate(" + value + "px,0)");
        }
        function alertDT(event, phase, direction, distance) {
			// tap needs to be captured differently when in need to break the autochange countdown
			if (doAutoChange) {
				doAutoChange = false;
				$("#autoChange").hide()
			} else {
				popup("#returnHomeBanner", 1000);
			}
        }
		function autoSiteChange() {
			$("#autoChange").show();
			doAutoChange = true;
			setTimeout(function(){
				$("#autoChangeCountdown").text("2")
			}, 1000);
			setTimeout(function(){
				$("#autoChangeCountdown").text("1")
			}, 2000);
			setTimeout(function(){
				$("#autoChangeCountdown").text("0")
			}, 3000);
			setTimeout(function(){
				if (doAutoChange) {
					window.location.href="{% url 'presentation:member' researcher.nextR.id %}"; 
				} else {
					$("#autoChangeCountdown").html("3");	
					setTimeout(autoSiteChange, autoSiteChangeTime);			
				}
			}, 3010);
		}
		function popup(obj, t=1000) {
			$(obj).show(200).delay(t).hide(500);
		}
        function backHome(event, phase, direction, distance) {
            window.location.href="{% url 'presentation:index' %}";
        }
        /**
         * Catch each phase of the swipe.
         * move : we drag the div
         * cancel : we animate back to where we were
         * end : we animate to the next image
         */
        function swipeStatusImg(event, phase, direction, distance) {
            //If we are moving before swipe, and we are going L or R in X mode, or U or D in Y mode then drag.
			//alert("you touched the image!");
            if (phase == "move" && (direction == "left" || direction == "right")) {
                var duration = 0;

                if (direction == "left") {
                    scrollImages((IMG_WIDTH * currentImg) + distance, duration);
                } else if (direction == "right") {
                    scrollImages((IMG_WIDTH * currentImg) - distance, duration);
                }

            } else if (phase == "cancel") {
                scrollImages(IMG_WIDTH * currentImg, speed);
            } else if (phase == "end") {
                if (direction == "right") {
                    previousImage();
                } else if (direction == "left") {
                    nextImage();
                }
            }
        }

        function previousImage() {
            currentImg = Math.max(currentImg - 1, 0);
            scrollImages(IMG_WIDTH * currentImg, speed);
        }

        function nextImage() {
            currentImg = Math.min(currentImg + 1, maxImages - 1);
            scrollImages(IMG_WIDTH * currentImg, speed);
        }

        /**
         * Manually update the position of the imgs on drag
         */
        function scrollImages(distance, duration) {
            imgs.css("transition-duration", (duration / 1000).toFixed(1) + "s");

            //inverse the number we set in the css
            var value = (distance < 0 ? "" : "-") + Math.abs(distance).toString();
            imgs.css("transform", "translate(" + value + "px,0)");
        }
		/* **************************************** */
    </script>
    
</body>
</html>